// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ChooseAreaSrc: typeof import('./../src/components/chooseArea/src/index.vue')['default']
    ChooseIconSrc: typeof import('./../src/components/chooseIcon/src/index.vue')['default']
    ChooseTimeSrc: typeof import('./../src/components/chooseTime/src/index.vue')['default']
    ContainerSrc: typeof import('./../src/components/container/src/index.vue')['default']
    ContainerSrcNavHeader: typeof import('./../src/components/container/src/navHeader/index.vue')['default']
    ContainerSrcNavSide: typeof import('./../src/components/container/src/navSide/index.vue')['default']
    ListSrc: typeof import('./../src/components/list/src/index.vue')['default']
    MenusSrc: typeof import('./../src/components/menus/src/index.vue')['default']
    NotificationSrc: typeof import('./../src/components/notification/src/index.vue')['default']
    ProgressSrc: typeof import('./../src/components/progress/src/index.vue')['default']
    TrendSrc: typeof import('./../src/components/trend/src/index.vue')['default']
  }
}

export { }
